name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: xcodebuild -scheme AppIconGenerator-Package build -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 12 Pro'
